### ISSUE TITLE
When use ConditionalContainer inside tabs package page is not loading.

### ISSUE THREAD

**Issue by lvdhoorn** [dcasia/conditional-container#13]
If the ConditionalContainer is inside a tabs package (https://github.com/eminiarts/nova-tabs package) on a edit resource page and the condition is true the page is not loading anymore.

**Comment by bolechen** [comment]
+1

**Comment by gldrenthe89** [comment]
+1

**Comment by milewski** [comment]
Well.... I tried to solve it but was a bit hard to fix without changing the nova-tabs package itself... So I have built my own tab solution to avoid that problem... https://github.com/dcasia/resource-navigation-tab perhaps this package also works on your case?

**Comment by lvdhoorn** [comment]
The Tabs package you created looks great but i think the https://github.com/eminiarts/nova-tabs is used a lot and it would be nice if the ConditionalContainer and the nova-tabs package would work together. I think the ConditionalContainer is essential if you have a bit more complex resources. Can we ask nova-tabs to change something? What was the problem?

**Comment by gldrenthe89** [comment]
+1

**Comment by jeffreydevreede** [comment]
would like to see a fix for this

**Comment by lvdhoorn** [comment]
Oke i did a little more research and i found out that the meta`tab` is not passed down to the child fields inside ConditionalContainer.

So this does not work:

 ```
ConditionalContainer::make([
                            Text::make('Description'),
])->if('invoice_period = ten_days OR invoice_period = monthly'),
```

But this does:
 ```
ConditionalContainer::make([
                            Text::make('Description')->withMeta(['tab' => 'example']),
])->if('invoice_period = ten_days OR invoice_period = monthly'),
```

So the withMeta that is on a ConditionalContainer should be passed to the child fields.

**Comment by milewski** [comment]
Fixed on version [v1.1.5](https://github.com/dcasia/conditional-container/releases/tag/v1.1.5) 🎉

**Comment by lvdhoorn** [comment]
It is working now! Thanks for the fix!

**Comment by bolechen** [comment]
> It is working now! Thanks for the fix!

is any why to condition set the whole tab panel show or hidden? thx.

**Comment by lvdhoorn** [comment]
Are you using the latest version of the conditional container? And witch tabs package are you using?

**Comment by bolechen** [comment]
thx for reply.

![out](https://user-images.githubusercontent.com/195015/70433435-b91bc480-1abc-11ea-832c-17dd324199e5.gif)

I used the last `eminiarts/nova-tabs` package, and i record a screencast to explain my problem. In this case, when i click the hidden toggle field, the `ConditionalContainer` is empty tab, i want to hidden them at all.

**Comment by milewski** [comment]
@bolechen I think an easy way to fix your issue would be by having another conditional container with the inverse operation `vip_pack = false` that contains a `Header` field within with a message like `Not applicable if you are are not a VIP` etc..
