### ISSUE TITLE
nova-belongsto-depend not working inside conditional-container

### ISSUE THREAD

**Issue by lvdhoorn** [dcasia/conditional-container#15]
When you use the nova-belongsto-depend package (https://github.com/orlyapps/nova-belongsto-depend) inside a conditional container the nova-belongsto-depend package stops working. You will get an error like: ```Class name must be a valid object or a string```.

The problem is that when you use the nova-belongsto-depend inside the conditional container the ```resourceClass``` parameter is not filled anymore.

**Comment by milewski** [comment]
@lvdhoorn can you try again with the latest version? I think I just closed this issue: https://github.com/dcasia/conditional-container/issues/16 which had the same problem with `resourceClass` perhaps that also fix this issue?

**Comment by lvdhoorn** [comment]
It did not fix the problem :(. The tabs are working like a charm now so that is a good thing!

**Comment by milewski** [comment]
Can you share a sample of your `fields()` method using the two package together

**Comment by lvdhoorn** [comment]
Yes i can ;).

```
return [
            new Panel('Invoicing', [
                Select::make('Invoice Period', 'invoice_period')
                    ->options([
                        'never'     => 'Never',
                        'ten_days'  => 'Ten days',
                        'monthly'   => 'Monthly',])
                    ->sortable()
                    ->displayUsingLabels()
                    ->rules('required'),

                ConditionalContainer::make([

                    NovaBelongsToDepend::make('Company', 'messageDebtorCompany', 'App\Nova\Company')
                        ->options(Company::all())
                        ->fillUsing(function(){})
                        ->hideFromIndex(),

                    NovaBelongsToDepend::make('Debtor', 'messageDebtor', 'App\Nova\Debtor')->optionsResolve(function ($company) {
                        return $company->debtors()->get(['id', 'company_name', 'debtor_code']);
                        })->dependsOn('messageDebtorCompany')
                        ->hideFromIndex(),
                ])->if('invoice_period = ten_days OR invoice_period = monthly'),
            ])
        ];
```

**Comment by lvdhoorn** [comment]
I created a PR for the package https://github.com/orlyapps/nova-belongsto-depend/pull/54 that solve this problem.

**Comment by milewski** [comment]
Well... accessing the `->fields` direcly may be problematicly, did you see if it worked on all the view `edit / form` view without problem?  because the way the conditional container works is by "returning an empty" fields array if the necessary condition wasnt met , 

and it does it by either calling `resolveDependencyFieldUsingRequest()` or `resolveDependencyFieldUsingResource()`
