### ISSUE TITLE
BelongsTo not working inside container

### ISSUE THREAD

**Issue by timcv** [dcasia/conditional-container#16]
Hi,

When i put a regular BelongsTo field in the ConditionalContainer i get the following error.

/vendor/laravel/nova/src/Http/Controllers/AssociatableController.php:25
"Trying to get property 'resourceClass' of non-object"

This is found on row 25 in AssociatableController.php
```
$withTrashed = $this->shouldIncludeTrashed(
    $request, $associatedResource = $field->resourceClass
);
```

The problem seemes to be that the $field value is NULL.

My code:

```
ConditionalContainer
    ::make([
        BelongsTo::make('End user')
            ->sortable()
            ->rules('required'),
        ])
        ->if('is_checked truthy false'),

Boolean::make('Is checked', 'is_checked')
                ->hideFromIndex(),
```

Do you have any ideas?

/Tim

**Comment by timcv** [comment]
When im trying to update a resource, with a belongsTo field, i get the following error:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'end_user' in 'field list' (SQL: update `sp` set `persons` = [], `end_user` = ?, `sp`.`updated_at` = 2019-12-05 10:11:33 where `id` = 247)
```

**Comment by milewski** [comment]
Fixed on version [v1.1.4](https://github.com/dcasia/conditional-container/releases/tag/v1.1.4)

**Comment by timcv** [comment]
Dame, you are awesome!! #YEAH

**Comment by timcv** [comment]
Hi,

I just realized the field inside the container is hidden from index.

I Want the field to always be shown on index, but be conditional on forms.

Do you have any idea?

/Tim

**Comment by milewski** [comment]
yes that's actually on purpose, if you have these fields for example: `name`, `age` and you conditionally show the field `name` based on `age`, your index view would be all messed up, as some records would have `2` columns and others just `1` 

so your table would look something like this:

| Name    | Age |
|----------|----|
| 50       |    |
| Nolan    | 10 |
| Arabella | 24 |
| Sallie   | 30 |
| 60       |    |
| 65       |    |

**Comment by timcv** [comment]
Yes, that would not be good.

For now i solved the issue by adding the field outside the container and added ->onlyOnIndex() to that field..

Do you think its possible to add an option to show "missing" fields as empty on index? It could be an method like ->showFieldsOnIndex() on the ConditionalContainer field?

/Tim

**Comment by milewski** [comment]
It might be possible to add some extra logic to detect if it's index view, if so don't remove the field but instead set its value to null, you can open another issue with this suggestion as enhancement, when I have time I can give it a try

**Comment by timcv** [comment]
Thank you mate, i created an issue!
