### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by timcv** [dcasia/conditional-container#18]
Would it be possible to make this package work in Action modals?

/Tim

**Comment by milewski** [comment]
Yes!! But I'm bit busy right now with some other projects, might take a while until I can handle this... If you know how to implement please give it a try :)

**Comment by QQ879** [comment]
Any updates on this feature?

**Comment by jonasbrenig** [comment]
I just found out that this is not supported.

I would appreciate it as well. :-)

**Comment by QQ879** [comment]
> I just found out that this is not supported.
> 
> I would appreciate it as well. :-)

If you really need this feature in actions, you can use this for now: epartment/nova-dependency-container

**Comment by jonasbrenig** [comment]
> > I just found out that this is not supported.
> > I would appreciate it as well. :-)
> 
> If you really need this feature in actions, you can use this for now: epartment/nova-dependency-container

Thanks, but I will just use two actions to solve my problem for now.
I want o minimize additional packages, especially if they mostly serve the same purpose.

**Comment by dollypizzle** [comment]
Any update on this issue.

**Comment by dollypizzle** [comment]
> Any update on this issue.

@milewski please can you give updates or pointers on how to go about this

**Comment by milewski** [comment]
Hi @dollypizzle, I don't have time currently to add support to this, however If you are interested in submitting an PR with this change, you could start looking on how the nova-dependency-container package does it https://github.com/epartment/nova-dependency-container/blob/master/src/ActionHasDependencies.php, I noticed it has a trait is specifically for the action, also I believe no frontend code is necessary to be updated for make this to work

**Comment by qwertywelch** [comment]
Implemented by #60

**Comment by milewski** [comment]
Thanks @qwertywelch

**Comment by timcv** [comment]
@qwertywelch Mega! Thanks alot!

@milewski Could you make a new release so i can fetch this goodie?

**Comment by milewski** [comment]
It has been already released

**Comment by timcv** [comment]
Sorry that i disturbed you. I see it now. When i checked https://github.com/dcasia/conditional-container/releases it looked like 1.4.0 is released 24 mar :S

When checking the Tags view it looks correct "9 days ago".

Thanks a lot! It worked great!
