### ISSUE TITLE
Conditional statements referencing values within container don't work

### ISSUE THREAD

**Issue by PaulLawton227** [dcasia/conditional-container#20]
I have a ConditionalContainer to show and hide 'advanced options' for voucher codes and when I edit the Nova resource I want to test the contents of that container and show the container if it has some values set within it.

e.g. I want the following container to show if the min_basket field has a value. 
```        
Text::make( __('Code'),  'code')
            ->rules('required')
            ->sortable()
        ,                     
        ConditionalContainer::make([
            Text::make( __('Min Basket Value'),  'min_basket')
                ->hideFromIndex()
                ->sortable()
        ])->if('min_basket truthy true')
```
but it doesn't work.
However, if I use the 'code' field in the if statement e.g.
```        
Text::make( __('Code'),  'code')
            ->rules('required')
            ->sortable()
        ,                     
        ConditionalContainer::make([
            Text::make( __('Min Basket Value'),  'min_basket')
                ->hideFromIndex()
                ->sortable()
        ])->if('code truthy true')
```
then it does show and hide depending on the content of the field 'code'

Is this not possible to show/hide depending on fields within the container?

**Comment by milewski** [comment]
It doesn't make sense depend on a field that is within the container itself, in your example min_basket would be hidden at the very first render, how would ever be able to change the value of it? 

But even if you had a default value set and somehow it is visible on the form, this package don't check for internal fields. 

So it's not an issue, this decision was made by design, I'm not creating nor setting listener for fields that doesn't exist outside the container, so in your case min_basket should have never been visible on the page

**Comment by PaulLawton227** [comment]
Ok, no probs.
Just to let you know the reason for this request - the use case is as follows:

When creating the voucher resource, there are some options that are 'advanced options' which don't need to be visible on creation, unless the user chooses to 'see them'.  There is a checkbox to trigger the show and hide of the container ->if ('advanced_checkbox = 1').

When editing the voucher resource, I want to check if any of the advanced fields have any data in them and if they do - then default the container to be opened. e.g. ->if('advanced_field1 truthy true') ->if('advanced_field2 truthy true') so that the fields can be seen.

So effectively, have a checkbox to show and hide AND show based upon the content within the container.

**Comment by natbentley** [comment]
@milewski I'd like to give this a bump - one of the great potentials for ConditionalContainer is to be able to tidy up large forms into distinct sections that are shown/hidden, so I think you're missing the point of @PaulLawton227's ticket.

**Comment by milewski** [comment]
Im still not sure exactly sure of what would be the benefits of it.. from my point of view I see something like this happening:

```php
 ConditionalContainer::make([
            Text::make('Test')->withMeta([ 'value' => 'hello world' ])
        ])
        ->if('test === "hello world"')
```

So taking this example:

1 - The `Test` field starts with the value `hello world` so the conditional is met, so it`s visible on the page
2 - if user type anything on the field it will suddenly hide itself as the condition will evaluate to false
3 - There will be no way to bring the field back unless you refresh the page and start the form over again

So I think this is a bad UX

On @PaulLawton227 on your use case, I think you could just use multiple containers? it`s possible to nest containers within itself as long as they depend on outside fields for example:

```
Checkbox::make('checkbox'),

ConditionalContainer::make([
     Text::make('Demo'),

     ConditionalContainer::make([
         Text::make('Test')
     ])->if('demo contains 123"')

 ])->if('checkbox truthy true"'),

```
