### ISSUE TITLE
Passing a closure to if method throws an error

### ISSUE THREAD

**Issue by abishekrsrikaanth** [dcasia/conditional-container#23]
The `MorphTo` [example](https://github.com/dcasia/conditional-container#examples) here indicates a way to pass a closure to the `if` method, but doing so causes an error.

**Error:**

```
Argument 1 passed to 
App\Nova\InvoiceItem::DigitalCreative\ConditionalContainer\{closure}() 
must be of the type string, object given
```

**Comment by milewski** [comment]
@abishekrsrikaanth fixed on latest version
