### ISSUE TITLE
ConditionalContainer breaks benjaco/belongs-to-many

### ISSUE THREAD

**Issue by noahlocke** [dcasia/conditional-container#29]
I'm trying to use `benjacho/belongs-to-many` inside a conditional container. A few issues I've found:

1) If you use the native Nova `readonly()` method, the field is not disabled as it should be. The user can still interact with the input and change the value...however it appears that the field is still succesfully "read only" in the sesnse that the value does not change in the form object on submission... weird right? This ONLY happens when the field is wrapped in a ConditionalContainer. 

2) There is a weird error when trying to `update` a record and the `belongs-to-many` field is wrapped in a ConditionalContainer. It appears that the field is treated as a column rather than a pivot (belongs to many, so there's no "column" to update per-se).

**Comment by YarinceP** [comment]
I have the same problem.

**Comment by noahlocke** [comment]
@milewski any chance you could take a look?

**Comment by noahlocke** [comment]
@milewski any update?

**Comment by noahlocke** [comment]
@milewski any update?

**Comment by timcv** [comment]
I made a pull request that make sure BelongsToManyField is NOT treated as a column. While waiting for a merge, you can test my fork and see if it works for you to.

**Comment by timcv** [comment]
It was added in 1.2.1. Hope this solves your issues :)
