### ISSUE TITLE
TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by Milkhan** [dcasia/conditional-container#30]
Thank you for this very helpful package. 
I am getting 'TypeError: Cannot read property 'join' of undefined' error in all my resources. I tried all cases but no luck. I traced the error it is in FormField.vue:
`watchableAttributes() {
                return this.field.expressionsMap.join()
            }`

I am using:
Laravel Framework 7.4.0
Nova: v3.2.1

**Comment by Milkhan** [comment]
@milewski 
FYI,  I've changed 
`return this.field.expressionsMap.join()`
to 
`return this.field.expressions.join()`
in FormField.vue:
watchableAttributes() { return this.field.expressionsMap.join() } and it is working as expected now.

**Comment by milewski** [comment]
Well it needs to be the `expressionsMap.join()` otherwise, it won't work as expected on all view (edit/update) etc... I guess the issue is that you forgot to import the `use HasConditionalContainer` trait?

**Comment by Milkhan** [comment]
Yes, exactly, I forgot to import the use HasConditionalContainer:) Thank you for the quick response!
