### ISSUE TITLE
does not work with : fieldsForCreate, fieldsForUpdate

### ISSUE THREAD

**Issue by issour** [dcasia/conditional-container#31]
Hi,
As Documentation says :

Dynamic Field Methods Precedence ::
The fieldsForIndex, fieldsForDetail, fieldsForCreate, and fieldsForUpdate methods always take precedence over the fields method.
`$allFields = $this->fields($request);`
Many thx

**Comment by mennotempelaar** [comment]
@issour Can u check if this update fixes your issue?

**Comment by issour** [comment]
Hi @mennotempelaar i can't test because the correction is not pushed in 1.1.6 :
```
$method = $this->fieldsMethod($request);
$allFields = $this->{$method}($request);
```
Many thx !!

**Comment by mennotempelaar** [comment]
@issour You can if you change the version of the package within your composer.json file to `dev-master`:

```json
"digital-creative/conditional-container": "dev-master",
```

You can set it back to 1.1.6 afterwards. 😊

**Comment by milewski** [comment]
That's weird... the tag in github shows that it includes the right commit: https://github.com/dcasia/conditional-container/compare/v1.1.6...master however the version published to packagist dont. I will publish another version `1.1.7` see if packagist picks up the right commit

**Comment by milewski** [comment]
Actually my bad I tagged the wrong commit before. `1.1.7` includes the fix

**Comment by issour** [comment]
Awesome Thkx to you @milewski & @mennotempelaar 💯
