### ISSUE TITLE
fields inside the conditional wrapper is losing its expected value

### ISSUE THREAD

**Issue by marianne-fullstack** [dcasia/conditional-container#32]
The field inside the conditional container is losing its expected value..

![image](https://user-images.githubusercontent.com/53204251/81737746-2a77fd00-94cb-11ea-9d90-2c4e391d2615.png)

my code
![image](https://user-images.githubusercontent.com/53204251/81737340-89894200-94ca-11ea-9925-ba6d447c782e.png)

**Comment by sigaev-pro** [comment]
same issue!

**Comment by milewski** [comment]
Could it be because the `HasConditionalContainer` trait was forgotten? I can't replicate this
