### ISSUE TITLE
undefined method: fieldsMethod

### ISSUE THREAD

**Issue by anditsung** [dcasia/conditional-container#34]
anyone having this issue?

the method is missing?

**Comment by milewski** [comment]
Uhm this is supposed to be in Nova 3.* which version are you using?

**Comment by anditsung** [comment]
i see thats why. currently im using nova 2
should update the requirement for this field

**Comment by milewski** [comment]
you can install the previous version that was the only change made `composer require digital-creative/conditional-container:1.1.5`
