### ISSUE TITLE
Call to undefined method App\Nova\ResourceName::fieldsMethod() after updating to 1.1.7

### ISSUE THREAD

**Issue by adamcrampton** [dcasia/conditional-container#35]
The latest release causes this exception to be thrown
![image](https://user-images.githubusercontent.com/5696904/82381252-333d7580-9a6d-11ea-91a4-116edd2a5b33.png)

**Comment by anditsung** [comment]
New version for nova3

**Comment by adamcrampton** [comment]
Ah ok, just tried with a Nova 3 project and its fine. 

Sorry for the trouble
