### ISSUE TITLE
v1.1.7 reporting "call to undefined method App\Nova\Resource::fieldsMethod()"

### ISSUE THREAD

**Issue by TARichardWashington** [dcasia/conditional-container#36]
v1.1.6 totally fine.

![uh-oh](https://user-images.githubusercontent.com/12430546/82596385-186b1e00-9b9f-11ea-959c-f4c6657e3004.png)

**Comment by milewski** [comment]
Duplicated https://github.com/dcasia/conditional-container/issues/35
