### ISSUE TITLE
Problem on update "Unknown column 'conditional_container_xxx"

### ISSUE THREAD

**Issue by nicolaeum** [dcasia/conditional-container#37]
Hi. I'm having some issues when I try to update any value inside a ConditionalContainer

On create its all good and custom validation works perfect, but on updates it breaks because of 

Column not found: 1054 Unknown column 'conditional_container_umis8ij2m2' in 'field list'

It fails on any Resource update:
Column not found: 1054 Unknown column 'conditional_container_n78s7zhuvv' in 'field list' (SQL: update `campaign_criteria` set `active` = 1, `conditional_container_n78s7zhuvv` = ?, `conditional_container_69av6xtx9w` = ?, `conditional_container_6ankofrrcr` = ?, `conditional_container_pefz0rbda2` = ?, `conditional_container_jlugbekiw0` = ?, `conditional_container_tkhlt2gubt` = ?, `conditional_container_jjqnarr4jk` = ?, `conditional_container_nn34aros7g` = ?, `campaign_criteria`.`updated_at` = 2020-05-26 18:16:11 where `id` = 18) 

And during the insert in action_events table
insert into `action_events` (`batch_id`, `user_id`, `name`, `actionable_type`, `actionable_id`, `target_type`, `target_id`, `model_type`, `model_id`, `fields`, `original`, `changes`, `status`, `exception`, `updated_at`, `created_at`) values ('90a77423-e5dc-40c4-8945-df74098de0fc', 1, 'Update', 'App\Models\CampaignCriteria', 18, 'App\Models\CampaignCriteria', 18, 'App\Models\CampaignCriteria', 18, '', '{\"active\":1}', '{\"active\":true,\"conditional_container_3ywtvpnayw\":null,\"conditional_container_nidwiv6qkk\":null,\"conditional_container_vnulqwmmn0\":null,\"conditional_container_jdj8oty4yh\":null,\"conditional_container_txpqr8vmqe\":null,\"conditional_container_8x87gkuoo8\":null,\"conditional_container_d10f8ut25a\":null,\"conditional_container_p1csk2kjhn\":null}', 'finished', '', '2020-05-26 10:27:04', '2020-05-26 10:27:04')

Any idea?

Thanks!

**Comment by Israel5** [comment]
Hi, I'm also with this very same problem, and I have no idea how to solve that.

My setup is:
PHP 7.4.7
Laravel 7.19.0
Nova 3.6.0

I can create a resource normally, but when I try to update it, I get this error.
```
SQLSTATE[42703]: Undefined column: 7 ERROR:  column "conditional_container_9rsqbluhxt" of relation "cases" does not exist↵LINE 1: ...pments_type_ftl" = $1, "shipments_type_ltl" = $2, "condition...↵                                                             ^ (SQL: update "cases" set "shipments_type_ftl" = 1, "shipments_type_ltl" = 1, "conditional_container_9rsqbluhxt" = ?, "conditional_container_n6ugooqkx4" = ?, "updated_at" = 2020-07-18 08:55:50 where "id" = 2)
```

Any idea or workaround? I have a project to be delivered by the next few weeks and I'd appreciate a way to solve it.

Thanks.

**Comment by abishekrsrikaanth** [comment]
@milewski, I get the same error when I use this nova package https://github.com/ebess/advanced-nova-media-library. Could you advice how to resolve this?
