### ISSUE TITLE
How to work with another packages that changes DOM too.

### ISSUE THREAD

**Issue by wemersonrv** [dcasia/conditional-container#4]
Hello.

Please see this issue in another package: https://github.com/armincms/nova-tab/issues/1

I'm using this `armincms/nova-tab` and as `conditional-container` changes the DOM, the component tab component does not works properly, because the fields array where changed with `conditional-container`

Can you please tell us a way to solve this when use `conditional-container ` alongside other components that changes DOM too?

**Comment by milewski** [comment]
@wemersonrv Hey I just got some time now to do a quick setup and try it out locally but it`s working for me, I have the following setup:

```
return Tab::make('tab-name', function ($tab) {

    $tab->group('first-tab-name', [

        Text::make('Name', 'name')->rules('required'),

        ConditionalContainer::make([

            Text::make('Test', 'test')->rules('required'),

        ])->if('name === works'),
      
    ]);

})->fullwidth()->toArray();
```

**Comment by wemersonrv** [comment]
> @wemersonrv Hey I just got some time now to do a quick setup and try it out locally but it`s working for me, I have the following setup:
> 
> ```
> return Tab::make('tab-name', function ($tab) {
> 
>     $tab->group('first-tab-name', [
> 
>         Text::make('Name', 'name')->rules('required'),
> 
>         ConditionalContainer::make([
> 
>             Text::make('Test', 'test')->rules('required'),
> 
>         ])->if('name === works'),
>       
>     ]);
> 
> })->fullwidth()->toArray();
> ```

Hello @milewski , test here and it works now. looking for their last releases, i realized that in latest releases they fix these erros when using it with another DOOM changer components like yours.

Cool. Liked your both components a lot... they are amazing togheter!

**Comment by milewski** [comment]
Okay, so the issues were with the other package., closing this for now
