### ISSUE TITLE
Versions greater than 1.1.6 are backwards incompatible with Nova 2.x branch.

### ISSUE THREAD

**Issue by bredmor** [dcasia/conditional-container#40]
ex. updating to `1.1.7`, `1.1.8` causes a hard break due to the addition of `$this->fieldsMethod($request)` in `src/HasConditionalContainer.php`

Releasing breaking changes in a patch version update is generally unexpected, should this not be in `conditional-container` 1.2.x or at least define nova 3.x as a dependency?

**Comment by milewski** [comment]
Sorry that was unexpected I generally thought that I had missed that from nova since from the beginning only to realize that was a new feature released later. I should had looked into the change history from nova before the update... I will track down the changes from nova onwards
