### ISSUE TITLE
Edit page is not loading with HasConditionalContainer

### ISSUE THREAD

**Issue by Slgoetz** [dcasia/conditional-container#42]
I updated to Nova  v3.12.0  and Conditional Container v1.2. When I did this my edit pages for the pages containing `ConditionalContainer` stopped loading.  It only happens after I added `Use HasConditionalContainer;`.  Without `HasConditionalContainer` I get the error of `TypeError: this.field.expressionsMap is undefined` but with it nothing shows up on the page. 

It does work as expected on Create, but once I save and try to edit the item it breaks and becomes hidden with no errors that I can see.

<img width="1061" alt="Screen Shot 2020-10-07 at 10 53 47 PM" src="https://user-images.githubusercontent.com/393000/95409594-f7a62980-08ef-11eb-8ef4-d4fd58b93bbf.png">

**Comment by httpware** [comment]
Did you manage to resolve this?

**Comment by bolechen** [comment]
can you try this PR will fix this? https://github.com/dcasia/conditional-container/pull/43

**Comment by milewski** [comment]
I publish the fix by @bolechen on `v1.2.1`

**Comment by httpware** [comment]
Erm, I have composer updated to get v1.2.1 and no Nova won't load it just timesout. 

When I roll back to v1.2.0 it loads but you can't edit. 

When using ConditionalContainer and JsonWrapper on the resource should you use: HasConditionalContainer or HasJsonWrapper? You can't use them together as they clash.

**Comment by httpware** [comment]
I am unsure if it's a clash with another package but the second I updated (without changing anything else) I now can't access Nova. It simply spins and times-out. I remove the package and it works fine.

The only other field I have that isn't a Nova one is JsonWrapper.

**Comment by httpware** [comment]
Hmm, thanks for looking into this.

I know find when using your package that my nova instance just times-out (504). The second I remove the package it works beautifully.

Will have to investigate.

**Comment by gabrielesbaiz** [comment]
It's a bit weird, but on Nova v3.12.1 version 1.2.0 worked.
Now with v1.2.1 the edit page is just like @Slgoetz said.
Rolling back to v1.2.0 the edit page works perfectly.
