### ISSUE TITLE
help text is not showing

### ISSUE THREAD

**Issue by JonathanDoelan** [dcasia/conditional-container#49]
Hello.

Thx for your great work!
Unfortunately I’ve found a little bug. The following code does not show the help text on the front-end:

`ConditionalContainer::make([
	Text::make('title')
		->help(__('title-help')),
])
->if('title = yes'),`

**Comment by milewski** [comment]
fixed [v1.3.0](https://github.com/dcasia/conditional-container/releases/tag/v1.3.0)
