### ISSUE TITLE
Fields Are Not Updating

### ISSUE THREAD

**Issue by Milkhan** [dcasia/conditional-container#59]
Nova 3.23.1 
The fields inside the conditional field are not updating. I tried number, text and other fields.

**Comment by aliozgurr** [comment]
Same here, I'm using a select field inside the conditional field and it doesn't saves the value. But the select field works outside of the conditional field.

**Comment by theianjohnson** [comment]
Is this package no longer working with the latest Nova then?

**Comment by milewski** [comment]
I'm using it with the latest nova version as of today `v3.29.0`, and see no issue with it, if you can show an example code that has an issue would be helpful.. but it is mostly like you might have forgotten to add the `HasConditionalContainer` trait to your resource...
