### ISSUE TITLE
Show on not null select value?

### ISSUE THREAD

**Issue by dormadekhin** [dcasia/conditional-container#6]
How to display a field if the value is not NULL?

` ConditionalContainer::make([
              //...
            ])->if('direction_to'),`

**Comment by milewski** [comment]
did you try:

`ConditionalContainer::make([ //... ])->if('direction_to truthy true')`

**Comment by dormadekhin** [comment]
yes it helped, only now errors appear in the browser console
![image](https://user-images.githubusercontent.com/32381310/68540584-13930980-03c7-11ea-8f4d-594832a1625f.png)

```php
Fields\BelongsTo::make($this->getLabel('direction_to'), 'directionTo', Direction::class)->nullable(),
ConditionalContainer::make([
  Fields\Select::make($this->getLabel('transport_type_to'), 'transport_type_to')->options($this->getList('transport_type'))->nullable(true)->displayUsingLabels(),
  DateTime::make($this->getLabel('departure_datetime'), 'departure_datetime')
        ->placeholder(false)
        ->timeFormat('HH:mm')->locale('ru'),
  Fields\Text::make($this->getLabel('flight_number'), 'flight_number_to'),
])->if('directionTo truthy true')
```
the problem is only with the text field, if you remove it there are no errors

**Comment by milewski** [comment]
Try the latest version: [v1.1.1](https://github.com/dcasia/conditional-container/releases/tag/v1.1.1), I have fixed some issues with `BelongsTo` field it might fix the issue you were having
