### ISSUE TITLE
field not shown in index view

### ISSUE THREAD

**Issue by ZoreAnkit** [dcasia/conditional-container#67]
I have following code

```
ConditionalContainer::make([
                        Text::make(__('Order No'), 'order_number')->nullable()->showOnIndex(),
                    ])
                        ->if('category = small_project OR category = big_project'),
```

I do not see this field in index view check below image for ref

![Selection_103](https://user-images.githubusercontent.com/46300882/152318980-e8be8495-d961-460d-86c0-f42bd0803df4.png)

**Comment by milewski** [comment]
That is right, fields are removed from the index view on purpose. as this could break your table.. imagine the first row has 5 columns.. but the second has 10... it would completely break the layout

**Comment by ZoreAnkit** [comment]
What do i do if i want to show field in index view?

**Comment by milewski** [comment]
You can define the method `fieldsForIndex() { }` and return all the fields you need visible on the index..

**Comment by ZoreAnkit** [comment]
Thank you so much for the package. Above solution works for showing fields in index view even if they are declared in conditional container.
