### ISSUE TITLE
Adding conditional fields to a Nova resource which are NOT fields in the DB.

### ISSUE THREAD

**Issue by PaulLawton227** [dcasia/conditional-container#7]
We have a voucher model, which has percentage and fixed discount fields.

I have a conditional dropdown to show and hide these fields using your packag e.g.
```
Select::make('Type', 'type')
            ->options([
                1 => 'Fixed Amount',
                2 => 'Percentage',
            ]),
```

However, there is no need to save this 'type' in the database.  
The problem is that when we save this resource - it complains that 'type' is not a field in the database.  

Is there any way to make Nova ignore certain fields like this?

**Comment by milewski** [comment]
It's not possible, because even if you pass the form step on the form view the package would require to know which option you choose in order to show the correct fields on the details / index view..

**Comment by timcv** [comment]
@PaulLawton227 I hav not tried it with this field, but this technique might work for you.

This example shows how you can remove properties from the model before saving the model to the DB. It works by hooking in to the "saving" event and removing the type. When the model is fetched you set the type based on your other fields.

```
class ExampleModel extends Model
{
    protected static function boot()
    {
        parent::boot();

        self::saving(function ($model) {
            /*
             * Remove type from saved data because there is no real field.
             */
            unset($model->type);
        });

        self::retrieved(function (License $license) {
            /*
             * Set the type property so its present when loading the model
             */        
            $license->type = INSERT LOGIC TO DETERMINE YOUR TYPE
        });
    }
```

Dose this work for you?

//Tim

**Comment by PaulLawton227** [comment]
Thank you Tim - that worked a treat.
