### ISSUE TITLE
if condition not working with boolean values

### ISSUE THREAD

**Issue by ZoreAnkit** [dcasia/conditional-container#70]
Following is my code

```
Boolean::make(__('Standard'), 'is_standard')
                ->default(false),
            ConditionalContainer::make([
                BelongsTo::make(__('Task Category'), 'taskCategory', 'App\Nova\TaskCategory'),
            ])
                ->if('is_standard truthy true'),
            ConditionalContainer::make([
                Text::make(__('Task') . ' ' . __('Custom'), 'custom_task_title')
                    ->hideFromIndex(),
            ])
                ->if('is_standard truthy false'),
```

While creating new record i can see 2nd conditional container as default and when I try to toggle boolean the truthy conditons are not working

When boolean value is true 
![Selection_113](https://user-images.githubusercontent.com/46300882/153215677-5b721557-0545-4621-8372-f342c69ed3d7.png)

When boolean value is false
![Selection_115](https://user-images.githubusercontent.com/46300882/153216067-771cc17d-febf-417f-8794-503c8dae1f33.png)

From above images you can see when boolean value is true i should have seen belongs to field but instead its showing text field.

**Comment by milewski** [comment]
Fixed in [v1.4.2](https://github.com/dcasia/conditional-container/releases/tag/v1.4.2)
